# Generated by Django 5.1.3 on 2025-04-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название цепочки')),
                ('file_url', models.URLField(max_length=500, verbose_name='Ссылка на файл')),
                ('input_url', models.URLField(max_length=500, verbose_name='Ссылка на входные данные')),
            ],
        ),
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название модели')),
                ('api_url', models.URLField(max_length=500, verbose_name='API URL')),
                ('api_key', models.CharField(max_length=255, verbose_name='API ключ')),
            ],
        ),
    ]
