# Generated by Django 5.1.3 on 2025-04-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmchain',
            name='file_url',
            field=models.CharField(max_length=500, verbose_name='Ссылка на файл'),
        ),
        migrations.AlterField(
            model_name='llmchain',
            name='input_url',
            field=models.CharField(max_length=500, verbose_name='Ссылка на входные данные'),
        ),
    ]
