# Generated by Django 5.1.3 on 2025-04-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0002_alter_llmchain_file_url_alter_llmchain_input_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmmodel',
            name='model_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название модели для кода'),
        ),
    ]
