# Generated by Django 5.1.3 on 2025-05-12 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0005_llmchain_use_results'),
        ('programs', '0040_remove_semester_zet_taken_semester_plan_disc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmchainrun',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_chain_runs', to='programs.program', verbose_name='Программа ОП'),
        ),
    ]
