# Generated by Django 5.1.3 on 2025-05-16 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0008_llmchainrun_user_llmmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llmmessage',
            name='llm_chain',
        ),
        migrations.AddField(
            model_name='llmmessage',
            name='llm_chain_run',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='llm.llmchainrun', verbose_name='Запуск цепочки'),
            preserve_default=False,
        ),
    ]
