# Generated by Django 5.1.3 on 2025-05-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0010_llmchain_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmchain',
            name='inputs',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Входные данные'),
        ),
        migrations.AddField(
            model_name='llmchain',
            name='prompt',
            field=models.TextField(blank=True, null=True, verbose_name='Промпт'),
        ),
    ]
