# Generated by Django 5.1.3 on 2024-11-13 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=500)),
                ('level', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'education_directions',
            },
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'education_levels',
            },
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.TextField()),
                ('short_nominative', models.CharField(max_length=191)),
                ('short_genitive', models.CharField(max_length=191)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NsiType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.IntegerField()),
                ('part', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('code', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Тип НСИ',
                'verbose_name_plural': 'Типы НСИ',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ProgramRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'program_roles',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=255)),
                ('annotation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.IntegerField(default=1)),
                ('form', models.CharField(choices=[('Очная', 'Очная'), ('Очно-заочная', 'Очно-заочная'), ('Заочная', 'Заочная')], default='Очная', max_length=20)),
                ('max_semesters', models.PositiveIntegerField(null=True)),
                ('fgos_file', models.FileField(blank=True, null=True, upload_to='fgos_files/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to=settings.AUTH_USER_MODEL)),
                ('direction_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='programs.direction')),
                ('level_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='programs.educationlevel')),
            ],
            options={
                'db_table': 'programs',
            },
        ),
        migrations.CreateModel(
            name='Nsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_name', models.CharField(blank=True, max_length=2000, null=True)),
                ('start_date', models.CharField(blank=True, max_length=100, null=True)),
                ('accept_date', models.CharField(blank=True, max_length=100, null=True)),
                ('accept_number', models.CharField(blank=True, max_length=100, null=True)),
                ('nsiDate', models.DateField(blank=True, null=True)),
                ('nsiNumber', models.CharField(blank=True, max_length=191, null=True)),
                ('nsiEdit', models.CharField(blank=True, max_length=191, null=True)),
                ('nsiName', models.TextField(blank=True, null=True)),
                ('nsiApproveName', models.CharField(blank=True, max_length=191, null=True)),
                ('nsiProtocolDate', models.DateField(blank=True, null=True)),
                ('nsiCode', models.CharField(blank=True, max_length=191, null=True)),
                ('nsiPeriod', models.CharField(blank=True, max_length=191, null=True)),
                ('nsiBasis', models.TextField(blank=True, null=True)),
                ('nsiAuthors', models.TextField(blank=True, null=True)),
                ('nsiEditor', models.CharField(blank=True, max_length=191, null=True)),
                ('nsiCity', models.CharField(blank=True, max_length=191, null=True)),
                ('nsiYear', models.IntegerField(blank=True, null=True)),
                ('nsiPages', models.CharField(blank=True, max_length=200, null=True)),
                ('nsiProtocolNumber', models.CharField(blank=True, max_length=191, null=True)),
                ('nsiLink', models.TextField(blank=True, null=True)),
                ('nsiFullName', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('nsiMinistry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.ministry')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.nsitype')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.program')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='programs.program')),
                ('role_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.programrole')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'program_users',
            },
        ),
    ]
