# Generated by Django 5.1.3 on 2024-11-20 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_remove_program_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('stage_number', models.PositiveIntegerField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='programs.program')),
            ],
            options={
                'ordering': ['program', 'stage_number'],
                'unique_together': {('program', 'stage_number')},
            },
        ),
    ]
