# Generated by Django 5.1.3 on 2024-11-20 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('stage_number', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['stage_number'],
            },
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='stage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stage',
            name='stage_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='programs.stagetype'),
        ),
        migrations.RemoveField(
            model_name='stage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='stage_number',
        ),
    ]
