# Generated by Django 5.1.3 on 2024-11-20 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_stage_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.PositiveIntegerField()),
                ('chunks', models.JSONField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('stage_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='programs.stagetype')),
            ],
        ),
        migrations.CreateModel(
            name='StageStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunks', models.JSONField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_steps', to='programs.stage')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_steps', to='programs.step')),
            ],
        ),
    ]
