# Generated by Django 5.1.3 on 2024-11-21 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_step_stagestep'),
    ]

    operations = [
        migrations.CreateModel(
            name='WizardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='step',
            name='stage_type',
        ),
        migrations.AddField(
            model_name='stagetype',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Wizard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wizards', to='programs.program')),
                ('wizard_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.wizardtype')),
            ],
        ),
        migrations.CreateModel(
            name='StepType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=255, null=True)),
                ('position', models.PositiveIntegerField()),
                ('wizard_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_types', to='programs.wizardtype')),
            ],
        ),
        migrations.DeleteModel(
            name='StageStep',
        ),
        migrations.DeleteModel(
            name='Step',
        ),
    ]
