# Generated by Django 5.1.3 on 2024-11-21 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_wizardtype_remove_step_stage_type_stagetype_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('chunks', models.JSONField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('step_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.steptype')),
                ('wizard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='programs.wizard')),
            ],
        ),
    ]
