# Generated by Django 5.1.3 on 2024-11-21 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('nsis', models.ManyToManyField(related_name='products', to='programs.nsi')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='programs.program')),
            ],
        ),
    ]
