# Generated by Django 5.1.3 on 2024-11-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
