# Generated by Django 5.1.3 on 2024-11-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0010_product_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nsis',
            field=models.ManyToManyField(blank=True, related_name='products', to='programs.nsi'),
        ),
    ]
