# Generated by Django 5.1.3 on 2024-11-27 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0012_step_result_json'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direction',
            options={'ordering': ['created_at'], 'verbose_name': 'Направление обучения', 'verbose_name_plural': 'Направления обучения'},
        ),
        migrations.AlterModelOptions(
            name='educationlevel',
            options={'ordering': ['created_at'], 'verbose_name': 'Уровень образования', 'verbose_name_plural': 'Уровни образования'},
        ),
        migrations.AlterModelOptions(
            name='ministry',
            options={'ordering': ['created_at'], 'verbose_name': 'Министерство', 'verbose_name_plural': 'Министерства'},
        ),
        migrations.AlterModelOptions(
            name='nsi',
            options={'ordering': ['created_at'], 'verbose_name': 'НСИ', 'verbose_name_plural': 'НСИ'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['program', 'position'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': 'Программа', 'verbose_name_plural': 'Программы'},
        ),
        migrations.AlterModelOptions(
            name='programrole',
            options={'ordering': ['created_at'], 'verbose_name': 'Роль', 'verbose_name_plural': 'Роли'},
        ),
        migrations.AlterModelOptions(
            name='programuser',
            options={'verbose_name': 'Роль пользователя', 'verbose_name_plural': 'Роли пользователя'},
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['program'], 'verbose_name': 'Этап разработки программы', 'verbose_name_plural': 'Этапы разработки программ'},
        ),
        migrations.AlterModelOptions(
            name='stagetype',
            options={'ordering': ['stage_number'], 'verbose_name': 'Тип этап разработки', 'verbose_name_plural': 'Типы этапов разработки'},
        ),
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['created_at'], 'verbose_name': 'Шаг ИИ', 'verbose_name_plural': 'Шаги ИИ'},
        ),
        migrations.AlterModelOptions(
            name='steptype',
            options={'ordering': ['position'], 'verbose_name': 'Тип шага', 'verbose_name_plural': 'Типы шагов'},
        ),
        migrations.AlterModelOptions(
            name='wizard',
            options={'ordering': ['created_at'], 'verbose_name': 'Мастер ИИ', 'verbose_name_plural': 'Мастера ИИ'},
        ),
        migrations.AlterModelOptions(
            name='wizardtype',
            options={'verbose_name': 'Тип мастера', 'verbose_name_plural': 'Типы мастеров'},
        ),
    ]
