# Generated by Django 5.1.3 on 2024-11-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0013_alter_direction_options_alter_educationlevel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nsis',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='programs.nsi'),
        ),
    ]
