# Generated by Django 5.1.3 on 2024-11-29 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0014_alter_product_nsis'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('position', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('nsis', models.ManyToManyField(blank=True, null=True, related_name='lifestages', to='programs.nsi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='programs.product')),
            ],
            options={
                'verbose_name': 'Этап ЖЦ',
                'verbose_name_plural': 'Этапы ЖЦ',
                'ordering': ['product', 'position'],
            },
        ),
    ]
