# Generated by Django 5.1.3 on 2024-11-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0016_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifestage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
