# Generated by Django 5.1.3 on 2024-11-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0017_lifestage_description_process_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='nsis',
            field=models.ManyToManyField(blank=True, null=True, related_name='processes', to='programs.nsi'),
        ),
    ]
