# Generated by Django 5.1.3 on 2024-12-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0018_process_nsis'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiplicityTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('position', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Тип кратности',
                'verbose_name_plural': 'Типы кратности',
                'ordering': ['position'],
            },
        ),
    ]
