# Generated by Django 5.1.3 on 2024-12-02 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0019_multiplicitytypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifestage',
            name='nsis',
            field=models.ManyToManyField(blank=True, related_name='lifestages', to='programs.nsi'),
        ),
        migrations.AlterField(
            model_name='process',
            name='nsis',
            field=models.ManyToManyField(blank=True, related_name='processes', to='programs.nsi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nsis',
            field=models.ManyToManyField(blank=True, related_name='products', to='programs.nsi'),
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=355)),
                ('description', models.TextField(blank=True, null=True)),
                ('task', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Профессиольные', 'Профессиольные'), ('Общепрофессиональные', 'Общепрофессиональные'), ('Общие', 'Общие')], default='Очная', max_length=20)),
                ('position', models.PositiveIntegerField()),
                ('multiplicity_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplines', to='programs.multiplicitytypes')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='programs.program')),
            ],
        ),
    ]
