# Generated by Django 5.1.3 on 2024-12-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0020_alter_lifestage_nsis_alter_process_nsis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='type',
            field=models.CharField(choices=[('Профессиольные', 'Профессиольные'), ('Общепрофессиональные', 'Общепрофессиональные'), ('Общие', 'Общие')], max_length=30),
        ),
    ]
