# Generated by Django 5.1.3 on 2024-12-02 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0021_alter_discipline_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MultiplicityTypes',
            new_name='MultiplicityType',
        ),
    ]
