# Generated by Django 5.1.3 on 2024-12-02 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0022_rename_multiplicitytypes_multiplicitytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=355)),
                ('code', models.CharField(max_length=355)),
                ('position', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='discipline',
            name='type',
            field=models.CharField(choices=[('Профессиольные', 'Профессиольные'), ('Общепрофессиональные', 'Общепрофессиональные'), ('Универсальные', 'Универсальные')], max_length=30),
        ),
        migrations.AddField(
            model_name='discipline',
            name='competence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplines', to='programs.competence'),
        ),
    ]
