# Generated by Django 5.1.3 on 2024-12-02 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0023_competence_alter_discipline_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='programs.program'),
            preserve_default=False,
        ),
    ]
