# Generated by Django 5.1.3 on 2024-12-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0024_competence_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='type',
            field=models.CharField(choices=[('Профессиольные', 'Профессиольные'), ('Общепрофессиональные', 'Общепрофессиональные'), ('Универсальные', 'Универсальные')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
