# Generated by Django 5.1.3 on 2024-12-02 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0025_competence_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competence',
            options={'ordering': ['program', 'position'], 'verbose_name': 'Компетенция', 'verbose_name_plural': 'Компетенции'},
        ),
    ]
