# Generated by Django 5.1.3 on 2024-12-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0026_alter_competence_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
