# Generated by Django 5.1.3 on 2024-12-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0027_competence_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='area',
            field=models.TextField(blank=True, null=True),
        ),
    ]
