# Generated by Django 5.1.3 on 2024-12-06 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0028_discipline_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='programs.program')),
            ],
        ),
        migrations.CreateModel(
            name='SemesterDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zet', models.PositiveIntegerField(default=0)),
                ('control', models.CharField(max_length=20, null=True)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.discipline')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.semester')),
            ],
        ),
        migrations.AddField(
            model_name='semester',
            name='disciplines',
            field=models.ManyToManyField(related_name='semesters', through='programs.SemesterDiscipline', to='programs.discipline'),
        ),
    ]
