# Generated by Django 5.1.3 on 2024-12-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0029_semester_semesterdiscipline_semester_disciplines'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='processes',
            field=models.ManyToManyField(related_name='disciplines', to='programs.process'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='products',
            field=models.ManyToManyField(related_name='disciplines', to='programs.product'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='stages',
            field=models.ManyToManyField(related_name='disciplines', to='programs.lifestage'),
        ),
    ]
