# Generated by Django 5.1.3 on 2024-12-09 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0030_discipline_processes_discipline_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='processes',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='products',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='stages',
        ),
        migrations.AddField(
            model_name='lifestage',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages', to='programs.discipline'),
        ),
        migrations.AddField(
            model_name='process',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processes', to='programs.discipline'),
        ),
        migrations.AddField(
            model_name='product',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='programs.discipline'),
        ),
    ]
