# Generated by Django 5.1.3 on 2024-12-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0031_remove_discipline_processes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='type',
            field=models.CharField(choices=[('Профессиональные', 'Профессиональные'), ('Общепрофессиональные', 'Общепрофессиональные'), ('Универсальные', 'Универсальные')], max_length=30),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='type',
            field=models.CharField(choices=[('Профессиональные', 'Профессиональные'), ('Общепрофессиональные', 'Общепрофессиональные'), ('Универсальные', 'Универсальные')], max_length=30),
        ),
    ]
