# Generated by Django 5.1.3 on 2024-12-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0032_alter_competence_type_alter_discipline_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semesterdiscipline',
            name='control',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='semesterdiscipline',
            name='zet',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
