# Generated by Django 5.1.3 on 2024-12-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0033_alter_semesterdiscipline_control_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semesterdiscipline',
            name='control',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
