# Generated by Django 5.1.3 on 2024-12-24 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0034_alter_semesterdiscipline_control'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('default', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.CreateModel(
            name='ProgramSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='programs.program')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='programs.setting')),
            ],
            options={
                'verbose_name': 'Настройка программы',
                'verbose_name_plural': 'Настройки программ',
            },
        ),
    ]
