# Generated by Django 5.1.3 on 2024-12-25 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0036_activities'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activities',
            new_name='Activity',
        ),
    ]
