# Generated by Django 5.1.3 on 2024-12-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0037_rename_activities_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='zqt_taken',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
