# Generated by Django 5.1.3 on 2024-12-26 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0038_semester_zqt_taken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='zqt_taken',
            new_name='zet_taken',
        ),
    ]
