# Generated by Django 5.1.3 on 2024-12-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0039_rename_zqt_taken_semester_zet_taken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='zet_taken',
        ),
        migrations.AddField(
            model_name='semester',
            name='plan_disc',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='plan_zet',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
