# Generated by Django 5.1.3 on 2024-11-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('programs', '0004_stagetype_alter_stage_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GPTChat',
            new_name='GPTChain',
        ),
    ]
