# Generated by Django 5.1.3 on 2024-11-20 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_rename_gptchat_gptchain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='chat',
            new_name='chain',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='MessageFile',
        ),
    ]
