# Generated by Django 5.1.3 on 2024-11-21 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_rename_chat_message_chain_remove_message_sender_and_more'),
        ('programs', '0009_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gptchain',
            name='stage',
        ),
        migrations.AddField(
            model_name='gptchain',
            name='wizard',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='programs.wizard'),
        ),
    ]
