# Generated by Django 5.1.3 on 2024-11-22 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_remove_gptchain_stage_gptchain_wizard'),
        ('programs', '0011_alter_product_nsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='programs.step'),
        ),
    ]
