# Generated by Django 5.1.3 on 2024-11-27 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_message_step'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gptchain',
            options={'ordering': ['created_at'], 'verbose_name': 'Цепочка сообщение', 'verbose_name_plural': 'Цепочки сообщений'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
